name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Xcode build
        run: make build
      # - name: Xcode test
      #   run: xcodebuild -project Treon.xcodeproj -scheme Treon -configuration Debug test -only-testing:TreonTests
      - name: Enforce file/function size limits
        run: |
          # Fail if any Swift file exceeds 500 lines
          OVER=0
          while IFS= read -r -d '' f; do
            L=$(wc -l < "$f" | tr -d ' ')
            if [ "$L" -gt 500 ]; then echo "Too many lines ($L): $f"; OVER=1; fi
          done < <(git ls-files '*.swift' -z)
          # Fail if any function exceeds 50 lines (heuristic)
          while IFS= read -r -d '' f; do
            if awk '/^[[:space:]]*(public|internal|private)?[[:space:]]*func[[:space:]]/{c=0; fn=1} fn{if($0 ~ /\{/) c++; if($0 ~ /\}/) c--; if($0 ~ /\}/ && c==0){fn=0} if(fn) l++; if(!fn && l>50){print "Function too long (" l "): " FILENAME; exit 1}}' "$f"; then :; else OVER=1; fi
          done < <(git ls-files '*.swift' -z)
          if [ "$OVER" -ne 0 ]; then exit 1; fi

