name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Xcode build
        run: make build
      # - name: Xcode test
      #   run: xcodebuild -project Treon.xcodeproj -scheme Treon -configuration Debug test -only-testing:TreonTests
      - name: Enforce file/function size limits
        run: bash scripts/ci_check.sh

